### ISSUE TITLE
新版的burp爆错

### ISSUE THREAD

**Issue by admin1test** [z2p/sweetPotato#16]
使用新版本burp：2023.11.3
![image](https://github.com/z2p/sweetPotato/assets/17872611/4bc1e7f4-ac5e-4c4e-bc12-7259f584359b)
at burp.Ztek.ZS(Unknown Source)
	at burp.Zvdk.ZE(Unknown Source)
	at burp.Zc_m.Za(Unknown Source)
	at burp.Zxbp.Zn(Unknown Source)
	at burp.Zxbp.Zt(Unknown Source)
	at burp.Zxbp.ZI(Unknown Source)
	at burp.Zimg.ZI(Unknown Source)
	at burp.Zz8a.ZI(Unknown Source)
	at burp.Zie8.ZI(Unknown Source)
	at burp.Zj5z.ZO(Unknown Source)
	at burp.Zxiu.ZG(Unknown Source)
	at burp.Zxin.ZG(Unknown Source)
	at burp.Zcd_.ZM(Unknown Source)
	at burp.Zqm.ZI(Unknown Source)
	at burp.Zqm.ZJ(Unknown Source)
	at burp.Zef8.ZT(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy23.sendRequest(Unknown Source)
	at burp.Zd6o.makeHttpRequest(Unknown Source)
	at burp.Zii9.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Ztd2.makeHttpRequest(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:241)
	at burp.BurpExtender$4.run(BurpExtender.java:194)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "burp.Ui.Tags.getMain2Tag()" because "this.tags" is null
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:103)
	at burp.Zehm.handleHttpRequestToBeSent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy24.handleHttpRequestToBeSent(Unknown Source)
	at burp.Ztee.Zl(Unknown Source)
	at burp.Zpzz.Zl(Unknown Source)
	at burp.Ztek.Zl(Unknown Source)
	at burp.Zvdk.ZK(Unknown Source)
	at burp.Zxbp.Zt(Unknown Source)
	at burp.Zxbp.ZI(Unknown Source)
	at burp.Zimg.ZI(Unknown Source)
	at burp.Zz8a.ZI(Unknown Source)
	at burp.Zie8.ZI(Unknown Source)
	at burp.Zj5z.ZO(Unknown Source)
	at burp.Zxiu.ZG(Unknown Source)
	at burp.Zxin.ZG(Unknown Source)
	at burp.Zcd_.ZM(Unknown Source)
	at burp.Zqm.ZI(Unknown Source)
	at burp.Zqm.ZJ(Unknown Source)
	at burp.Zef8.ZT(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy23.sendRequest(Unknown Source)
	at burp.Zd6o.makeHttpRequest(Unknown Source)
	at burp.Zii9.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Ztd2.makeHttpRequest(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:241)
	at burp.BurpExtender$4.run(BurpExtender.java:194)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "burp.Ui.Tags.getMain2Tag()" because "this.tags" is null
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:103)
	at burp.Zehm.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy24.handleHttpResponseReceived(Unknown Source)
	at burp.Ztee.ZS(Unknown Source)
	at burp.Zpzz.ZS(Unknown Source)
	at burp.Ztek.ZS(Unknown Source)
	at burp.Zvdk.ZE(Unknown Source)
	at burp.Zc_m.Za(Unknown Source)
	at burp.Zxbp.Zn(Unknown Source)
	at burp.Zxbp.Zt(Unknown Source)
	at burp.Zxbp.ZI(Unknown Source)
	at burp.Zimg.ZI(Unknown Source)
	at burp.Zz8a.ZI(Unknown Source)
	at burp.Zie8.ZI(Unknown Source)
	at burp.Zj5z.ZO(Unknown Source)
	at burp.Zxiu.ZG(Unknown Source)
	at burp.Zxin.ZG(Unknown Source)
	at burp.Zcd_.ZM(Unknown Source)
	at burp.Zqm.ZI(Unknown Source)
	at burp.Zqm.ZJ(Unknown Source)
	at burp.Zef8.ZT(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy23.sendRequest(Unknown Source)
	at burp.Zd6o.makeHttpRequest(Unknown Source)
	at burp.Zii9.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Ztd2.makeHttpRequest(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:241)
	at burp.BurpExtender$4.run(BurpExtender.java:194)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "burp.Ui.Tags.getMain2Tag()" because "this.tags" is null
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:103)
	at burp.Zehm.handleHttpRequestToBeSent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy24.handleHttpRequestToBeSent(Unknown Source)
	at burp.Ztee.Zl(Unknown Source)
	at burp.Zpzz.Zl(Unknown Source)
	at burp.Ztek.Zl(Unknown Source)
	at burp.Zvdk.ZK(Unknown Source)
	at burp.Zxbp.Zt(Unknown Source)
	at burp.Zxbp.ZI(Unknown Source)
	at burp.Zimg.ZI(Unknown Source)
	at burp.Zz8a.ZI(Unknown Source)
	at burp.Zie8.ZI(Unknown Source)
	at burp.Zj5z.ZO(Unknown Source)
	at burp.Zxiu.ZG(Unknown Source)
	at burp.Zxin.ZG(Unknown Source)
	at burp.Zcd_.ZM(Unknown Source)
	at burp.Zqm.ZI(Unknown Source)
	at burp.Zqm.ZJ(Unknown Source)
	at burp.Zef8.ZT(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy23.sendRequest(Unknown Source)
	at burp.Zd6o.makeHttpRequest(Unknown Source)
	at burp.Zii9.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Ztd2.makeHttpRequest(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:241)
	at burp.BurpExtender$4.run(BurpExtender.java:194)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "burp.Ui.Tags.getMain2Tag()" because "this.tags" is null
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:103)
	at burp.Zehm.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy24.handleHttpResponseReceived(Unknown Source)
	at burp.Ztee.ZS(Unknown Source)
	at burp.Zpzz.ZS(Unknown Source)
	at burp.Ztek.ZS(Unknown Source)
	at burp.Zvdk.ZE(Unknown Source)
	at burp.Zc_m.Za(Unknown Source)
	at burp.Zxbp.Zn(Unknown Source)
	at burp.Zxbp.Zt(Unknown Source)
	at burp.Zxbp.ZI(Unknown Source)
	at burp.Zimg.ZI(Unknown Source)
	at burp.Zz8a.ZI(Unknown Source)
	at burp.Zie8.ZI(Unknown Source)
	at burp.Zj5z.ZO(Unknown Source)
	at burp.Zxiu.ZG(Unknown Source)
	at burp.Zxin.ZG(Unknown Source)
	at burp.Zcd_.ZM(Unknown Source)
	at burp.Zqm.ZI(Unknown Source)
	at burp.Zqm.ZJ(Unknown Source)
	at burp.Zef8.ZT(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at burp.Zef8.sendRequest(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zi4l.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy23.sendRequest(Unknown Source)
	at burp.Zd6o.makeHttpRequest(Unknown Source)
	at burp.Zii9.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Zmb.makeHttpRequest(Unknown Source)
	at burp.Ztd2.makeHttpRequest(Unknown Source)
	at burp.BurpExtender.checkVul(BurpExtender.java:241)
	at burp.BurpExtender$4.run(BurpExtender.java:194)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by admin1test** [comment]
@z2p

**Comment by cyumik52** [comment]
-Dfile.encoding=utf-8 是utf-8 编码的问题，使用  -Dfile.encoding=utf-8 该配置启动burpsuite 即可,burpsuite 默认GBK
